---
name: "Release to staging"
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  deploy:
    uses: ./.github/workflows/workflow_release.yaml
    secrets:
      PAT: ${{ secrets.NHOST_PAT }}
      IMAGE: ${{ secrets.IMAGE_STAGING }}:456
      SERVICE_ID: ${{ secrets.SERVICE_ID_STAGING }}
