---
name: "Release to production"
on:
  push:
    branches:
      - 'main'


jobs:
  deploy:
    uses: ./.github/workflows/wg_test_and_release.yaml
    secrets:
      PAT: ${{ secrets.NHOST_PAT }}
      IMAGE: ${{ secrets.IMAGE_PRODUCTION }}:${{ github.sha }}
      SERVICE_ID: ${{ secrets.SERVICE_ID_PRODUCTION }}
