---
name: "Release to staging"
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  deploy:
    uses: nhost-actions/workflows/.github/workflows/build-and-release-nhost-run.yaml@first
    secrets:
      PAT: ${{ secrets.NHOST_PAT }}
      IMAGE: ${{ secrets.IMAGE_STAGING }}:${{ github.sha }}
      SERVICE_ID: ${{ secrets.SERVICE_ID_STAGING }}
