---
name: "Release to production"
on:
  push:
    branches:
      - 'main'


jobs:
  deploy:
    uses: ./.github/workflows/workflow_release.yaml
    secrets:
      PAT: ${{ secrets.NHOST_PAT }}
      IMAGE: ${{secrets.IMAGE_PRODUCTION }}:${{ github.sha }}
