---
name: "Release to staging"
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test-and-deploy:
    uses: ./.github/workflows/wf_test_and_release.yaml
    with:
      # IMAGE: ${{ secrets.IMAGE_STAGING }}:${{ github.sha }}
      IMAGE: sd:1.2.3
      SERVICE_ID: ${{ secrets.SERVICE_ID_STAGING }}
    secrets:
      PAT: ${{ secrets.NHOST_PAT }}
