---
name: "Release to staging"
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  deploy:
    uses: ./.github/workflows/wf_test_and_release.yaml
    secrets:
      PAT: ${{ secrets.NHOST_PAT }}
      IMAGE: ${{ secrets.IMAGE_STAGING }}:${{ github.sha }}
      SERVICE_ID: ${{ secrets.SERVICE_ID_STAGING }}
