---
name: "Release to production"
on:
  push:
    branches:
      - 'main'


jobs:
  test-and-deploy:
    uses: ./.github/workflows/wf_test_and_release.yaml
    with:
      IMAGE: ${{ secrets.IMAGE_PRODUCTION }}:${{ github.sha }}
      SERVICE_ID: ${{ secrets.SERVICE_ID_PRODUCTION }}
    secrets:
      PAT: ${{ secrets.NHOST_PAT }}
